(package "ccls"
         "0.1"
         "ccls client for lsp-mode")

(website-url "https://github.com/MaskRay/emacs-ccls")
(keywords "languages" "lsp" "c++")

(package-file "ccls.el")

(files "*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "27.1")
(depends-on "lsp-mode")
(depends-on "dash")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
